### Get all users
GET https://localhost:7123/users
Accept: application/json


### Get a specific user by name
GET https://localhost:7123/users/Alice
Accept: application/json


### Create a new user
POST https://localhost:7123/users
Content-Type: application/json

{
    "Name": "Charlie",
    "Age": 28
}


### Update an existing user
PUT https://localhost:7123/users/Alice
Content-Type: application/json

{
    "Name": "Alice",
    "Age": 26
}


### Delete a user
DELETE https://localhost:7123/users/Charlie
Accept: application/json


### test error
GET https://localhost:7123/test-error
Accept: application/json